### ISSUE TITLE
minions is not showing modes that are autoloaded

### ISSUE THREAD

**Issue by LemonBreezes** [tarsius/minions#35]
Take for example `glasses-mode`. This mode is not loaded by default in my Emacs configuration but I would still like for it to appear in the minions menu. Adding it to `minions-available-modes` only makes `glasses-mode` display if `glasses` is not loaded.

**Comment by tarsius** [comment]
> Take for example `glasses-mode`.

This mode *is* autoloaded, go look at its definition to verify. If it is not autoloaded for you, then something is broken about your installation.

> This mode is not loaded by default in my Emacs configuration but I would still like for it to appear in the minions menu.

Adding an entry for an unavailable mode is not particular useful. It would not be possible to enable the mode by selecting the respective entry. For that to be possible it would need to be loaded already or we would need to know how it can be loaded, and if that is not the case, then the entry in the list could only serve to inform the user that "you claimed that there is such a mode (by adding it to `minions-available-modes`), but that is not actually the case".

Autoloading the mode (or any function and/or variable really) is the mechanism that makes something accessible without actually loading it just yet. It would not make sense for `minions` to implement some inferior, specialized mechanism to do the same.

The problem here is that your autoloads are somehow broken.

**Comment by LemonBreezes** [comment]
> > Take for example `glasses-mode`.
> 
> This mode _is_ autoloaded, go look at its definition to verify. If it is not autoloaded for you, then something is broken about your installation.
> 
> > This mode is not loaded by default in my Emacs configuration but I would still like for it to appear in the minions menu.
> 
> Adding an entry for an unavailable mode is not particular useful. It would not be possible to enable the mode by selecting the respective entry. For that to be possible it would need to be loaded already or we would need to know how it can be loaded, and if that is not the case, then the entry in the list could only serve to inform the user that "you claimed that there is such a mode (by adding it to `minions-available-modes`), but that is not actually the case".
> 
> Autoloading the mode (or any function and/or variable really) is the mechanism that makes something accessible without actually loading it just yet. It would not make sense for `minions` to implement some inferior, specialized mechanism to do the same.
> 
> The problem here is that your autoloads are somehow broken.

Hi Tarsius. Sorry I did not word this issue clearly. I meant that if a minor mode is autoloaded but not actually loaded, the minor mode would not show up in the minions menu, even if that minor mode is in `minions-available-modes`. I have PR'd a fix for this issue in #36.

**Comment by tarsius** [comment]
I understand now. I'll have to take another look. It seems that before fewer modes than documented were listed, while after you pr more are listed.

**Comment by tarsius** [comment]
I've just pushed a major rewrite. Please give it a spin.

**Comment by LemonBreezes** [comment]
> I've just pushed a major rewrite. Please give it a spin.

Hi Tarsius. Thanks for putting the time in to rewrite Minions. I see a lot more minor modes now and I'm a fan of the `more...` submenu a lot. But I notice now that the autoloaded modes in `minions-promoted-modes` which are still not loaded still do not show up in the minions menu. I would like, for example, for `highlight-changes-mode` to show up as disabled even though `highlight-changes-mode` has not been activated during the editing session yet.

**Comment by tarsius** [comment]
I completely broke the prominent modes feature but that's fixed now. It's goal is solely to display certain modes directly in the mode line as would have been done without the use of minions. The documentation used to say that it also affects the menu. That was never correct and I have removed that claim. You should be able to use the new `minions-promoted-modes` to force a mode to be displayed in the top menu.

**Comment by LemonBreezes** [comment]
> I completely broke the prominent modes feature but that's fixed now. It's goal is solely to display certain modes directly in the mode line as would have been done without the use of minions. The documentation used to say that it also affects the menu. That was never correct and I have removed that claim. You should be able to use the new `minions-promoted-modes` to force a mode to be displayed in the top menu.

Hi. I've been testing that, but it still does not show autoloaded minor modes which are not loaded. I think it should check if a minor mode is autoloaded and show it in the menu as disabled.
